name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm ci
        else
          echo "No package.json found, skipping npm install"
        fi
        
    - name: Run tests
      run: |
        if [ -f package.json ] && npm run test --if-present; then
          npm run test
        else
          echo "No tests configured, skipping test execution"
        fi
        
    - name: Build project
      run: |
        if [ -f package.json ] && npm run build --if-present; then
          npm run build
        else
          echo "No build script found, skipping build"
        fi
        
    - name: Lint code
      run: |
        if [ -f package.json ] && npm run lint --if-present; then
          npm run lint
        else
          echo "No lint script found, skipping linting"
        fi

  security:
    runs-on: ubuntu-latest
    # このジョブは必須ステータスとして設定される
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH,MEDIUM'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v4
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
        
    - name: Fail on critical vulnerabilities
      run: |
        if [ -f trivy-results.sarif ]; then
          # クリティカルな脆弱性がある場合は失敗
          if grep -q '"level":"error"' trivy-results.sarif; then
            echo "Critical vulnerabilities found!"
            exit 1
          fi
        fi
